query getGates {
  gates {
    id
    created
    name
    description
    lat
    long
  }
}

mutation createGate(
  $name: String!
  $description: String!
  $lat: String!
  $long: String!
) {
  createGate(lat: $lat, long: $long, description: $description, name: $name) {
    gate {
      id
    }
  }
}
