query history($gateid: String, $carId: String, $created: String) {
  history(gateId: $gateid, carId: $carId, created: $created) {
    id
    created
    car {
      id
      ownerName
      plateNumber
      color
    }
    gate {
      name
    }
  }
}
