mutation login(
  $username: String
  $email: String
  $password: String
  $fcm: String
) {
  login(
    username: $username
    password: $password
    email: $email
    fcmToken: $fcm
  ) {
    accessToken
  }
}
